workflows:
  flutter-apk-ipa:
    name: Build APK and IPA
    environment:
      flutter: 3.29.0
      xcode: latest
      vars:
        APP_VERSION: 1.0.0
        BUILD_NUMBER: 1
      groups:
        - app_store_credentials # Secure credentials group in Codemagic UI
    scripts:
      - name: Set version
        script: |
          flutter clean
          flutter pub get
          # flutter pub run flutter_launcher_icons:main
          # flutter pub run build_runner build --delete-conflicting-outputs
          flutter --version
          flutter build apk --release 
          # flutter build ios --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      # - build/ios/iphoneos/Runner.app
      # - build/ios/archive/*.xcarchive
      # - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - parthunagar9@gmail.com

  web-deploy-preview:
    name: Web Build & Firebase Preview Deploy
    environment:
      flutter: stable
      vars:
        FIREBASE_CHANNEL: cardmaker-95ba3
      # secure_files:
      #   - firebase-service-account.json
    scripts:
      - name: Install Firebase CLI
        script: |
          curl -sL https://firebase.tools | bash
      - name: Set up Firebase authentication
        script: |
          mkdir -p ~/.config/gcloud
          echo $firebase_service_account | base64 --decode > ~/.config/gcloud/application_default_credentials.json
      - name: Build Flutter Web
        script: flutter build web
      - name: Deploy to Firebase Hosting Preview
        script: |
          firebase deploy --only hosting --project your-project-id \
            --token "$FIREBASE_TOKEN" \
            --channel "$FIREBASE_CHANNEL" \
            --public build/web
    artifacts:
      - build/web/**