/*
// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
      // throw UnsupportedError(
      //   'DefaultFirebaseOptions have not been configured for web - '
      //   'you can reconfigure this by running the FlutterFire CLI again.',
      // );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    // apiKey: 'AIzaSyAUwrkTZWYuTMkkGQ5CVG0a8hYct-Fqxwc',
    apiKey: 'AIzaSyBes1d65Rf7VXXKffEDxTpjwtWaJY1-6Zs',
    appId: '1:830378510376:android:eb4db4a317a306b411cd1d',
    messagingSenderId: '830378510376',
    projectId: 'cardmaker-95ba3',
  );

  ///
  /// in progress
  ///
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUwrkTZWYuTMkkGQ5CVG0a8hYct-Fqxwc',
    appId: '1:830378510376:android:eb4db4a317a306b411cd1d',
    messagingSenderId: '830378510376',
    projectId: 'cardmaker-95ba3',
    // storageBucket: 'clu-mobile.appspot.com',
    // iosClientId: '49849915195-rpi1vuk7to45upgpo7onlca6hlohpjaa.apps.googleusercontent.com',
    iosBundleId: 'com.sparks.driveruser',
  );

  static const FirebaseOptions web = FirebaseOptions(
      // apiKey: 'AIzaSyAUwrkTZWYuTMkkGQ5CVG0a8hYct-Fqxwc',
      // authDomain: 'your-project.firebaseapp.com',
      // projectId: 'cardmaker-95ba3',
      // storageBucket: 'your-project.appspot.com',
      // messagingSenderId: 'your-sender-id',
      // appId: '1:830378510376:web:59d18e5ca9fb970b11cd1d',
      // measurementId: 'your-measurement-id',

      apiKey: "AIzaSyBes1d65Rf7VXXKffEDxTpjwtWaJY1-6Zs",
      authDomain: "cardmaker-95ba3.firebaseapp.com",
      databaseURL: "https://cardmaker-95ba3-default-rtdb.firebaseio.com",
      projectId: "cardmaker-95ba3",
      storageBucket: "cardmaker-95ba3.appspot.com",
      messagingSenderId: "830378510376",
      appId: "1:830378510376:web:59d18e5ca9fb970b11cd1d",
      measurementId: "G-N3M9MT7KL0");
}

 */