class ProjectUtils {
  static const List<String> banners = [
    // "assets/projects/snackbar.png",
    // "assets/projects/quranB.png",
    // "assets/projects/medkitB.png",
    // "assets/projects/hereiamB.png",
    // "assets/projects/covidB.png",
    "assets/work/pkg_banner1.png",
    "assets/work/anglo_banner2.png",
    "assets/work/woocom/woocom_banner1.png",
    "assets/work/reastaurant/reastaurant_banner1.png",
    "assets/work/quiz/banner1.png",
    "assets/work/etaxi/driver/driver_banner1.png",
  ];

  static const List<String> icons = [
    // "assets/projects/flutter.png",
    // "assets/projects/quran.png",
    // "assets/projects/medkit.png",
    // "assets/projects/hereiam.png",
    // "assets/projects/covid.png",
    // "assets/projects/messenger.png",
    // "assets/projects/flutter.png",
    // "assets/projects/earbender.png",
    // "assets/projects/java.png",
    // "assets/projects/android.png",
    // "assets/services/open_b.png",
    "assets/projects/flutter.png",
    "assets/work/anglo_logo.png",
    "assets/work/woocom/woocom_logo1.png",
    "assets/work/reastaurant/reastaurant_logo.png",
    "assets/work/quiz/logo1.png",
    "assets/work/etaxi/driver/logo.png",
    "assets/projects/flutter.png",
    "assets/projects/earbender.png",
    "assets/projects/java.png",
    "assets/projects/android.png",
    "assets/services/open_b.png",
  ];

  static const List<String> titles = [
    // "Awesome Snackbar Dart Package",
    // "The Holy Qur'an",
    // "MedKit",
    // "Here I Am",
    // "COVID-19",
    // "Messenger Chat Head UI",
    // "flutter.dev - Flutter Web",
    // "Earbender",
    // "File Transfer Protocol",
    // "My Order",
    // "Hidev",
    "SuggestionTextField Dart Package",
    "Anglo-Eastern",
    "Woocom",
    "Reastaurant UI Kit",
    "Quiz App",
    "ETaxi App",
    // "flutter.dev - Flutter Web",
    // "Earbender",
    // "File Transfer Protocol",
    // "My Order",
    // "Hidev",
  ];

  static const List<String> description = [
    // "A very unique dart package to uplift the snackbar experience in flutter. Available at pub.dev now!",
    // "Application of Holy book of Muslims, Al-Qur'an. Developed using Flutter. Powered with live RestAPI given in README.md",
    // "A Phramacy app developed using Flutter powered with Firebase as database with Doctor and Patient panels.",
    // "Here I am is an Alert app that Sends alert SMS holding your location (Address and Google Maps) to your loved ones.",
    // "A live trakcer for COVID19 stats across the Globe and my Home country Pakistan. It uses APIs so the data is live.",
    // "Tried to clone the famous Chat Heads by Facebook Messenger using Flutter. Its basically in-app not exactly like the original chat head.",
    // "Flutter Official Site clone using Flutter Web. Try the live site here. For the time being its not responsive fully so there might be responsiveness issues.",
    // "A concept of Music App developed using Flutter. Having functionality of playing Audio.",
    // "A simple GUI based Java application that sends file from Client to Server but not the other way around.",
    // "A concept app for self-services at various restaurants now a days. More like a Restaurant Ordering System.",
    // "Its my end semester project. The whole design I developed here is an inspiration from my favortie Flutter Developer Marcin Szałek and his blog Fidev."
    "A very unique dart package to Predictable Textfield. Available at pub.dev soon!",
    "Anglo-Eastern Ship Management offers its services to ship owners around the globe, serving all types and sizes of ships. This app brings 40 years of learning and experience to all aspects of ship & crew management, education & training of seafarers, technical services & commercial operations also supported by over 25 offices around world with our head office in Hong Kong.",
    "Woocom Mobile App Builder for WooCommerce will convert your WooCommerce Store into mobile app. It has better user experience with features & functionalities and it's fully compatible with your default WooCommerce Store. Provides user-friendly experience & enhances customers engagement over mobile platform.",
    "The Reastaurant Ui Kit app lets you order and pay with your phone, get rewards, find out about new items and offers, browse the menu, check nutritional information and more!",
    "Trivia Quiz App – put your intellect to the test! For trivia enthusiasts and those hungry for knowledge. Trivia Quiz quizlet kahoot game Millionaire show QuizApp quizzlet quizizz erudite quizzland crack let master kahoot kahot, quizzlet, code quiz free coding challenge online test puzzles code tricks exercises programming education academy gratis exam let tips skills.",
    "The ETaxi app offers the safest and easiest way to ride, with multiple travel options and well-protected rides. With more than 100 vehicles in 50+ cities, ETaxi is the most popular ride hailing service in Germany.",
    // "Flutter Official Site clone using Flutter Web. Try the live site here. For the time being its not responsive fully so there might be responsiveness issues.",
    // "A concept of Music App developed using Flutter. Having functionality of playing Audio.",
    // "A simple GUI based Java application that sends file from Client to Server but not the other way around.",
    // "A concept app for self-services at various restaurants now a days. More like a Restaurant Ordering System.",
    // "Its my end semester project. The whole design I developed here is an inspiration from my favortie Flutter Developer Marcin Szałek and his blog Fidev."
  ];

  static const List<String> links = [
    // "https://pub.dev/packages/awesome_snackbar_content",
    // "https://github.com/mhmzdev/The_Holy_Quran_App",
    // "https://github.com/mhmzdev/MedKit-Pharmacy-App-Using-Flutter",
    // "https://github.com/mhmzdev/Here-I-Am-Alert-App",
    // "https://github.com/mhmzdev/Covid19-Tracker-App",
    // "https://github.com/mhmzdev/Messenger-Chat-Head-Flutter-UI",
    // "https://github.com/mhmzdev/flutter.dev-Flutter-Web-Clone",
    // "https://github.com/mhmzdev/Earbender_Music_App",
    // "https://github.com/mhmzdev/FTP_GUI_Java",
    // "https://github.com/mhmzdev/My-Order-Resturant-Ordering-System",
    // "https://github.com/mhmzdev/Hidev_Web",
    "https://github.com/parthunagar/Suggestion_textfield_project",
    "https://github.com/mhmzdev/The_Holy_Quran_App",
    "https://github.com/parthunagar/woocom",
    "https://github.com/parthunagar/reastaurant_ui_kit",
    "https://github.com/parthunagar/quiz_app_trivia",
    "https://github.com/parthunagar/etaxi",
    // "https://github.com/mhmzdev/flutter.dev-Flutter-Web-Clone",
    // "https://github.com/mhmzdev/Earbender_Music_App",
    // "https://github.com/mhmzdev/FTP_GUI_Java",
    // "https://github.com/mhmzdev/My-Order-Resturant-Ordering-System",
    // "https://github.com/mhmzdev/Hidev_Web",
  ];
}
